# Первичный анализ данных: pandas, DataFrame и графики

В этом ноутбуке мы переходим от базового Python к работе с табличными данными.

Для аналитика данных это важный шаг: в реальной работе данные чаще всего представлены в виде таблиц — продажи, клиенты, заявки, платежи, товары, города, статусы, даты.

## Что мы изучим

1. Как представить данные в виде словаря Python.
2. Как превратить словарь в таблицу `DataFrame`.
3. Как посмотреть столбцы, строки и базовую статистику.
4. Как группировать данные по категориям.
5. Как строить сводные таблицы.
6. Как строить простые графики с помощью pandas и Matplotlib.

## Важно

Запускайте ячейки сверху вниз. Каждая следующая ячейка часто использует переменные, которые были созданы выше.

## 1. Подключаем библиотеки

Библиотека — это набор готовых инструментов.

В этом ноутбуке нам нужны:

- `pandas` — для работы с таблицами;
- `matplotlib.pyplot` — для построения графиков;
- `numpy` — для удобной работы с числовыми массивами в отдельных примерах.

Обычно библиотеки подключают в самом начале ноутбука.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print("Библиотеки подключены успешно")

Matplotlib is building the font cache; this may take a moment.

Библиотеки подключены успешно

## 2. Данные в виде словаря

Начнем с очень маленького набора данных о продажах по месяцам.

В Python словарь хранит данные в формате:

```python
ключ: значение
```

В нашем примере:

- ключ `"Месяц"` хранит список месяцев;
- ключ `"Продажи"` хранит список значений продаж.

Такой словарь уже похож на таблицу: каждый ключ можно представить как название столбца.

In [2]:
# Создадим простую таблицу с данными о продажах
sales_data = {
    "Месяц": ["Янв", "Фев", "Мар", "Апр"],
    "Продажи": [10, 14, 12, 18]
}

sales_data

{'Месяц': ['Янв', 'Фев', 'Мар', 'Апр'], 'Продажи': [10, 14, 12, 18]}

### Что мы видим

Сейчас это еще не таблица pandas. Это обычный словарь Python.

Но структура уже табличная:

| Месяц | Продажи |
|---|---:|
| Янв | 10 |
| Фев | 14 |
| Мар | 12 |
| Апр | 18 |

Такой формат часто используют для демонстрационных данных.

In [3]:
print("Месяцы:", sales_data["Месяц"])
print("Продажи:", sales_data["Продажи"])
print("Тип объекта sales_data:", type(sales_data))

Месяцы: ['Янв', 'Фев', 'Мар', 'Апр']
Продажи: [10, 14, 12, 18]
Тип объекта sales_data: <class 'dict'>

## 3. Превращаем словарь в DataFrame

`DataFrame` — это основная табличная структура в pandas.

Проще всего воспринимать `DataFrame` как таблицу, похожую на лист Excel:

- есть строки;
- есть столбцы;
- у каждого столбца есть название;
- у каждой строки есть индекс.

In [4]:
sales_df = pd.DataFrame(sales_data)
sales_df

  Месяц  Продажи
0   Янв       10
1   Фев       14
2   Мар       12
3   Апр       18

### Разбор результата

Мы получили таблицу из двух столбцов:

- `Месяц` — текстовый столбец;
- `Продажи` — числовой столбец.

Левая часть таблицы — это индекс строки. В нашем случае pandas автоматически создал индексы `0`, `1`, `2`, `3`.

In [5]:
print("Столбцы таблицы:", list(sales_df.columns))
print("Количество строк и столбцов:", sales_df.shape)

Столбцы таблицы: ['Месяц', 'Продажи']
Количество строк и столбцов: (4, 2)

## 4. Выбираем один столбец

Если нам нужен один столбец, мы обращаемся к нему по названию:

```python
df["Название столбца"]
```

Для аналитика это базовая операция: часто нужно отдельно взять выручку, количество, город, категорию или дату.

In [6]:
sales_df["Продажи"]

0    10
1    14
2    12
3    18
Name: Продажи, dtype: int64

### Важно: DataFrame и Series

Когда мы выбираем один столбец из `DataFrame`, pandas возвращает объект `Series`.

Можно сказать проще:

- `DataFrame` — таблица;
- `Series` — один столбец таблицы.

In [7]:
sales_series = sales_df["Продажи"]

print("Тип всей таблицы:", type(sales_df))
print("Тип одного столбца:", type(sales_series))

Тип всей таблицы: <class 'pandas.core.frame.DataFrame'>
Тип одного столбца: <class 'pandas.core.series.Series'>

## 5. Базовая статистика по числовому столбцу

Метод `.describe()` показывает краткую статистику по числовым данным.

Для продаж он помогает быстро понять:

- сколько значений есть в столбце;
- какое среднее значение;
- какое минимальное и максимальное значение;
- как распределены значения.

In [8]:
print("Статистика по продажам:")
print(sales_df["Продажи"].describe())

Статистика по продажам:
count     4.00000
mean     13.50000
std       3.41565
min      10.00000
25%      11.50000
50%      13.00000
75%      15.00000
max      18.00000
Name: Продажи, dtype: float64

### Как читать `.describe()`

Ключевые строки:

- `count` — количество значений;
- `mean` — среднее значение;
- `std` — стандартное отклонение, то есть насколько значения отличаются от среднего;
- `min` — минимум;
- `max` — максимум.

На начальном этапе достаточно уверенно понимать `count`, `mean`, `min` и `max`.

In [9]:
mean_sales = sales_df["Продажи"].mean()
min_sales = sales_df["Продажи"].min()
max_sales = sales_df["Продажи"].max()

print("Средние продажи:", mean_sales)
print("Минимальные продажи:", min_sales)
print("Максимальные продажи:", max_sales)

Средние продажи: 13.5
Минимальные продажи: 10
Максимальные продажи: 18

## 6. Первый график: продажи по месяцам

Таблица показывает точные значения, но график помогает быстрее увидеть динамику.

Линейный график удобно использовать, когда значения идут во времени: месяцы, недели, дни, кварталы.

In [10]:
sales_df.plot(
    x="Месяц",
    y="Продажи",
    kind="line",
    marker="o",
    title="Продажи по месяцам"
)

plt.xlabel("Месяц")
plt.ylabel("Продажи")
plt.grid(True)
plt.tight_layout()
plt.show()

/tmp/ipykernel_3361/4042834050.py:13: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### Контрольный вопрос

В каком месяце продажи были максимальными?

Подсказка: можно ответить глазами по графику или рассчитать через pandas.

In [11]:
max_row = sales_df.loc[sales_df["Продажи"].idxmax()]
print("Месяц с максимальными продажами:", max_row["Месяц"])
print("Значение продаж:", max_row["Продажи"])

Месяц с максимальными продажами: Апр
Значение продаж: 18

## 7. Более подробная таблица: категории, города и продажи

Теперь создадим таблицу, где есть не только месяц и продажи, но и категории товаров и города.

Такая структура ближе к реальной аналитике: продажи обычно нужно смотреть не только в целом, но и в разрезах.

Например:

- по категории товара;
- по городу;
- по менеджеру;
- по каналу продаж;
- по статусу заказа.

In [12]:
category_data = {
    "Категория": ["A", "A", "B", "B", "C"],
    "Продажи": [10, 15, 20, 25, 30],
    "Город": ["Москва", "СПб", "Москва", "СПб", "Казань"]
}

category_df = pd.DataFrame(category_data)
category_df

  Категория  Продажи   Город
0         A       10  Москва
1         A       15     СПб
2         B       20  Москва
3         B       25     СПб
4         C       30  Казань

## 8. Просмотр таблицы и выбор данных

Перед анализом полезно быстро посмотреть:

- первые строки;
- список столбцов;
- размер таблицы;
- конкретный столбец;
- конкретную строку.

In [13]:
print("Первые строки таблицы:")
print(category_df.head())

print("\nСтолбцы:", list(category_df.columns))
print("Размер таблицы:", category_df.shape)

Первые строки таблицы:
  Категория  Продажи   Город
0         A       10  Москва
1         A       15     СПб
2         B       20  Москва
3         B       25     СПб
4         C       30  Казань

Столбцы: ['Категория', 'Продажи', 'Город']
Размер таблицы: (5, 3)

### Выбираем столбец `Продажи`

Когда мы пишем `category_df["Продажи"]`, мы получаем только один столбец из таблицы.

In [14]:
category_df["Продажи"]

0    10
1    15
2    20
3    25
4    30
Name: Продажи, dtype: int64

### Выбираем первую строку через `.iloc[0]`

`.iloc` используется для выбора строк и столбцов по позиции.

Позиция начинается с нуля:

- первая строка — `0`;
- вторая строка — `1`;
- третья строка — `2`.

In [15]:
first_row = category_df.iloc[0]
print("Первая строка таблицы:")
print(first_row)

Первая строка таблицы:
Категория         A
Продажи          10
Город        Москва
Name: 0, dtype: object

## 9. Группировка данных через `groupby`

Группировка нужна, когда мы хотим посчитать показатель отдельно по каждой группе.

Например:

- средние продажи по категориям;
- сумма продаж по городам;
- количество заказов по статусам;
- средний чек по менеджерам.

Логика простая:

1. Выбираем столбец, по которому группируем.
2. Выбираем числовой столбец, который считаем.
3. Выбираем функцию: `sum`, `mean`, `count`, `max`, `min`.

In [16]:
mean_sales_by_category = category_df.groupby("Категория")["Продажи"].mean()

print("Средние продажи по категориям:")
print(mean_sales_by_category)

Средние продажи по категориям:
Категория
A    12.5
B    22.5
C    30.0
Name: Продажи, dtype: float64

### Сумма продаж по городам

Среднее значение отвечает на вопрос «сколько в среднем».  
Сумма отвечает на вопрос «сколько всего».

В бизнес-аналитике сумма продаж часто важнее среднего, если мы смотрим общий объем выручки.

In [17]:
total_sales_by_city = category_df.groupby("Город")["Продажи"].sum()

print("Суммарные продажи по городам:")
print(total_sales_by_city)

Суммарные продажи по городам:
Город
Казань    30
Москва    30
СПб       40
Name: Продажи, dtype: int64

### Группировка как таблица

Иногда удобнее получить результат не как `Series`, а как обычную таблицу `DataFrame`.

Для этого можно использовать `.reset_index()`.

In [18]:
total_sales_by_city_table = total_sales_by_city.reset_index()
total_sales_by_city_table

    Город  Продажи
0  Казань       30
1  Москва       30
2     СПб       40

## 10. Описательная статистика по всей таблице

Метод `.describe()` можно применить ко всему `DataFrame`.

pandas автоматически выберет числовые столбцы и рассчитает по ним статистику.

In [19]:
category_df.describe()

         Продажи
count   5.000000
mean   20.000000
std     7.905694
min    10.000000
25%    15.000000
50%    20.000000
75%    25.000000
max    30.000000

## 11. Сводная таблица

Сводная таблица помогает смотреть показатель сразу в двух разрезах.

Например, мы хотим увидеть средние продажи:

- по строкам — категории;
- по столбцам — города.

Это похоже на сводную таблицу в Excel.

In [20]:
pivot_source_data = {
    "Категория": ["A", "A", "B", "B", "C", "C"],
    "Город": ["Москва", "СПб", "Москва", "СПб", "Москва", "СПб"],
    "Продажи": [10, 15, 20, 25, 30, 35]
}

pivot_df = pd.DataFrame(pivot_source_data)

print("Исходная таблица:")
print(pivot_df)

Исходная таблица:
  Категория   Город  Продажи
0         A  Москва       10
1         A     СПб       15
2         B  Москва       20
3         B     СПб       25
4         C  Москва       30
5         C     СПб       35

### Строим сводную таблицу со средними продажами

Параметры `pd.pivot_table()`:

- `values="Продажи"` — какой показатель считаем;
- `index="Категория"` — что будет в строках;
- `columns="Город"` — что будет в столбцах;
- `aggfunc="mean"` — какую функцию применяем.

In [21]:
pivot_mean = pd.pivot_table(
    pivot_df,
    values="Продажи",
    index="Категория",
    columns="Город",
    aggfunc="mean"
)

pivot_mean

Город      Москва   СПб
Категория
A            10.0  15.0
B            20.0  25.0
C            30.0  35.0

### Сводная таблица с суммой продаж

Если нужно посмотреть общий объем продаж, используем `aggfunc="sum"`.

In [22]:
pivot_sum = pd.pivot_table(
    pivot_df,
    values="Продажи",
    index="Категория",
    columns="Город",
    aggfunc="sum"
)

pivot_sum

Город      Москва  СПб
Категория
A              10   15
B              20   25
C              30   35

### Типичная ошибка в сводных таблицах

Если неправильно указать название столбца, pandas выдаст ошибку.

Например, если написать `"продажи"` с маленькой буквы вместо `"Продажи"`, это будет другое имя столбца.

В pandas названия столбцов чувствительны к регистру.

In [23]:
print("Список точных названий столбцов:")
print(list(pivot_df.columns))

Список точных названий столбцов:
['Категория', 'Город', 'Продажи']

## 12. Matplotlib: из чего состоит график

В Matplotlib часто используются два объекта:

- `Figure` — вся область рисунка;
- `Axes` — конкретная область графика с осями X и Y.

Для начинающего уровня можно запомнить так:

- `fig` — лист, на котором рисуем;
- `ax` — сам график на этом листе.

In [24]:
x = [i for i in range(6)]
y1 = [i for i in x]
y2 = [i ** 2 for i in x]

print("x:", x)
print("y1 = x:", y1)
print("y2 = x**2:", y2)

x: [0, 1, 2, 3, 4, 5]
y1 = x: [0, 1, 2, 3, 4, 5]
y2 = x**2: [0, 1, 4, 9, 16, 25]

### Линейный график через `fig, ax = plt.subplots()`

Этот способ удобен, когда нужно более явно управлять графиком: названием, подписями осей, сеткой, легендой и аннотациями.

In [25]:
fig, ax = plt.subplots()

ax.plot(x, y1, marker="o", label="y = x")
ax.plot(x, y2, marker="s", label="y = x**2")

ax.set_title("Пример линейного графика")
ax.set_xlabel("Ось X")
ax.set_ylabel("Ось Y")
ax.grid(True)
ax.legend()

ax.annotate(
    "выделим точку",
    xy=(2, 4),
    xytext=(3, 5),
    arrowprops=dict(arrowstyle="->")
)

plt.show()

/tmp/ipykernel_3361/607181179.py:19: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 13. Простой линейный график через `plt.plot()`

`plt.plot()` — короткий способ построить линейный график.

Он хорошо подходит для простых учебных и быстрых аналитических графиков.

In [26]:
plt.plot(x, y1, marker="o", label="y = x")
plt.plot(x, y2, linestyle="--", marker="s", label="y = x**2")

plt.title("Линейная диаграмма")
plt.xlabel("Ось X")
plt.ylabel("Ось Y")
plt.legend()
plt.grid(True)
plt.show()

/tmp/ipykernel_3361/4126777153.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 14. Столбчатая диаграмма

Столбчатая диаграмма подходит, когда нужно сравнить категории.

Например:

- продажи по городам;
- количество клиентов по сегментам;
- число заявок по статусам;
- выручку по товарным категориям.

In [27]:
categories = ["A", "B", "C", "D", "E"]
values = np.array([5, 3, 7, 8, 6])

plt.bar(categories, values, label="Значения")

plt.title("Столбчатая диаграмма")
plt.xlabel("Категории")
plt.ylabel("Значения")
plt.legend()
plt.grid(axis="y")
plt.show()

/tmp/ipykernel_3361/4260613076.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### Горизонтальная столбчатая диаграмма

Горизонтальная диаграмма удобна, когда названия категорий длинные или когда нужно визуально сравнить значения по строкам.

In [28]:
plt.barh(categories, values, label="Значения")

plt.title("Горизонтальная столбчатая диаграмма")
plt.xlabel("Значения")
plt.ylabel("Категории")
plt.legend()
plt.grid(axis="x")
plt.show()

/tmp/ipykernel_3361/1518007544.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 15. Итоговая мини-практика: анализ заказов

Теперь объединим изученные действия в маленький аналитический сценарий.

У нас есть данные о заказах:

- номер заказа;
- город;
- категория товара;
- канал продаж;
- сумма заказа.

Нужно быстро понять:

1. Общую выручку.
2. Средний чек.
3. Выручку по городам.
4. Выручку по категориям и городам через сводную таблицу.
5. Как выглядит выручка по городам на графике.

In [29]:
orders_data = {
    "Заказ": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Город": ["Москва", "СПб", "Москва", "Казань", "СПб", "Москва", "Казань", "СПб"],
    "Категория": ["Ноутбуки", "Смартфоны", "Ноутбуки", "Аксессуары", "Смартфоны", "Аксессуары", "Ноутбуки", "Аксессуары"],
    "Канал": ["Сайт", "Сайт", "Маркетплейс", "Сайт", "Маркетплейс", "Сайт", "Маркетплейс", "Сайт"],
    "Сумма": [75000, 42000, 81000, 6500, 39000, 8200, 69000, 7100]
}

orders_df = pd.DataFrame(orders_data)
orders_df

   Заказ   Город   Категория        Канал  Сумма
0   1001  Москва    Ноутбуки         Сайт  75000
1   1002     СПб   Смартфоны         Сайт  42000
2   1003  Москва    Ноутбуки  Маркетплейс  81000
3   1004  Казань  Аксессуары         Сайт   6500
4   1005     СПб   Смартфоны  Маркетплейс  39000
5   1006  Москва  Аксессуары         Сайт   8200
6   1007  Казань    Ноутбуки  Маркетплейс  69000
7   1008     СПб  Аксессуары         Сайт   7100

### Считаем общую выручку и средний чек

- Общая выручка — сумма всех заказов.
- Средний чек — средняя сумма одного заказа.

In [30]:
total_revenue = orders_df["Сумма"].sum()
average_order_value = orders_df["Сумма"].mean()

print("Общая выручка:", total_revenue)
print("Средний чек:", round(average_order_value, 2))

Общая выручка: 327800
Средний чек: 40975.0

### Выручка по городам

Группируем таблицу по столбцу `Город` и считаем сумму по столбцу `Сумма`.

In [31]:
revenue_by_city = orders_df.groupby("Город")["Сумма"].sum().reset_index()
revenue_by_city

    Город   Сумма
0  Казань   75500
1  Москва  164200
2     СПб   88100

### Сводная таблица: категории × города

Теперь посмотрим, какие категории дают выручку в каждом городе.

In [32]:
revenue_pivot = pd.pivot_table(
    orders_df,
    values="Сумма",
    index="Категория",
    columns="Город",
    aggfunc="sum",
    fill_value=0
)

revenue_pivot

Город       Казань  Москва    СПб
Категория
Аксессуары    6500    8200   7100
Ноутбуки     69000  156000      0
Смартфоны        0       0  81000

### График выручки по городам

Для сравнения городов подойдет столбчатая диаграмма.

In [33]:
plt.bar(revenue_by_city["Город"], revenue_by_city["Сумма"])

plt.title("Выручка по городам")
plt.xlabel("Город")
plt.ylabel("Выручка")
plt.grid(axis="y")
plt.show()

/tmp/ipykernel_3361/1512166701.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 16. Самостоятельное задание

Используя таблицу `orders_df`, выполните задания ниже.

### Задание 1

Посчитайте выручку по каналам продаж.

Подсказка: сгруппируйте данные по столбцу `Канал` и посчитайте сумму по столбцу `Сумма`.

### Задание 2

Найдите максимальную сумму заказа.

Подсказка: используйте метод `.max()`.

### Задание 3

Постройте сводную таблицу, где:

- строки — `Канал`;
- столбцы — `Категория`;
- значения — сумма заказов.

In [34]:
# Задание 1. Выручка по каналам продаж
revenue_by_channel = orders_df.groupby("Канал")["Сумма"].sum().reset_index()
revenue_by_channel

         Канал   Сумма
0  Маркетплейс  189000
1         Сайт  138800

In [35]:
# Задание 2. Максимальная сумма заказа
max_order_sum = orders_df["Сумма"].max()
print("Максимальная сумма заказа:", max_order_sum)

Максимальная сумма заказа: 81000

In [36]:
# Задание 3. Сводная таблица: канал продаж × категория
channel_category_pivot = pd.pivot_table(
    orders_df,
    values="Сумма",
    index="Канал",
    columns="Категория",
    aggfunc="sum",
    fill_value=0
)

channel_category_pivot

Категория    Аксессуары  Ноутбуки  Смартфоны
Канал
Маркетплейс           0    150000      39000
Сайт              21800     75000      42000

## 17. Краткий итог

В этом ноутбуке мы прошли базовый путь аналитика в pandas:

1. Создали данные в виде словаря.
2. Преобразовали словарь в `DataFrame`.
3. Выбрали столбцы и строки.
4. Посчитали базовую статистику.
5. Сгруппировали данные через `groupby`.
6. Создали сводную таблицу через `pivot_table`.
7. Построили линейные и столбчатые графики.

Главная идея: pandas помогает быстро превращать сырые таблицы в аналитические выводы.